[package]
name = "cob_sickle_math"
version = "0.5.0-rc.3"
edition = "2021"
description = "Math dependencies for sickle_ui"
license = "MIT OR Apache-2.0"
repository = "https://github.com/UkoeHB/bevy_cobweb_ui"

[dependencies]
bevy_color = "0.15.0-rc.3"
bevy_reflect = "0.15.0-rc.3"
bevy_text = "0.15.0-rc.3"
bevy_ui = { version = "0.15.0-rc.3", features = ["bevy_text"] }
serde = { version = "1.0", features = ["derive"] }
