[package]
name = "bevy_cobweb_ui"
description = "UI tools and widgets built on bevy_cobweb and sickle_ui"
authors = ["koe <ukoe@protonmail.com>"]
version = "0.2.0"
edition = "2021"
keywords = ["gamedev", "reactive", "ui"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/UkoeHB/bevy_cobweb_ui"

[workspace]
members = [
    "bevy_cobweb_ui_derive",
    "examples/*",
]
exclude = [
    "examples/*",
]

[lib]
path = "src/lib.rs"
doctest = false
test = false

[[test]]
name = "tests"
path = "tests/test/mod.rs"
doctest = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["-Zunstable-options", "--cfg", "docsrs"]

[features]
# Default features.
default = ["widgets"]

# Enables built-in widgets.
widgets = []

# Enables hot-reloading. Note that `bevy/embedded_watcher` does not watch assets embedded in dependencies.
hot_reload = ["bevy/file_watcher", "bevy/embedded_watcher"]

# Dev features. Enables hot-reloading.
dev = ["hot_reload", "bevy/dynamic_linking"]

[dependencies]
bevy        = { version = "0.14", default-features = true, features = ["serialize"] }
bevy_cobweb = { version = "0.11.0" }
serde       = { version = "1.0" }
serde_json  = { version = "1.0", features = ["preserve_order"] }
smol_str    = { version = "0.2" }
smallvec    = { version = "1.13" }
thiserror   = { version = "1.0" }
tracing     = { version = "0.1" }

sickle_ui = { version = "0.2" }
#sickle_ui = { rev = "a0f42b2", git = "https://github.com/dead-money/sickle_ui" }
#sickle_ui = { rev = "f0593f9", git = "https://github.com/UmbraLuminosa/sickle_ui" }
#sickle_ui = { rev = "32b119b", git = "https://github.com/UkoeHB/sickle_ui" }

# Localization deps
sys-locale = { version = "0.3" }
fluent = { version = "0.16" }
fluent-langneg = { version = "0.14" }
fluent_content = { version = "0.0.5" }
intl-memoizer = { version = "0.5" }
ron = { version = "0.8" }
serde_yaml = { version = "0.9" }
unic-langid = { version = "0.9" }

# Local sub-crates
bevy_cobweb_ui_derive = { path = "bevy_cobweb_ui_derive", version = "0.1.0" }

[dev-dependencies]
tracing-subscriber = { version = "0.3" }

[profile.dev.package."*"]
opt-level = 2
