[package]
name = "bevy_cobweb_ui"
description = "UI tools and widgets built with bevy_cobweb"
authors = ["koe <ukoe@protonmail.com>"]
version = "0.0.3"
edition = "2021"
keywords = ["gamedev", "reactive", "ui"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/UkoeHB/bevy_cobweb_ui"

[workspace]
resolver = "2"
exclude = [
    "examples",
    "assets"
]

[lib]
path = "src/lib.rs"
doctest = false
test = false

[[test]]
name = "tests"
path = "tests/test/mod.rs"
doctest = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bevy        = { version = "0.13", default-features = true, features = ["serialize"] }
bevy_cobweb = { version = "0.6" }
serde       = { version = "1.0" }
serde_json  = { version = "1.0", features = ["preserve_order"] }
smol_str    = { version = "0.2" }
smallvec    = { version = "1.13" }
thiserror   = { version = "1.0" }
tracing     = { version = "0.1" }

#sickle_ui = { rev = "ed6d066", git = "https://github.com/UmbraLuminosa/sickle_ui" }
sickle_ui = { rev = "ccf01e5", git = "https://github.com/UkoeHB/sickle_ui" }

[dev-dependencies]
bevy               = { version = "0.13", default-features = true, features = ["dynamic_linking", "file_watcher"] }
tracing-subscriber = { version = "0.3" }
