[package]
name = "bevy_cobweb_ui_derive"
description = "Derives for bevy_cobweb_ui"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote = { version = "1.0" }
syn = { version = "2.0" }
proc-macro2 = "1.0"
